using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Bolter_XIV
{
    public class GameResources
    {
        protected readonly byte[] CliPosBytes = { 0xF3, 0x0F, 0x11, 0x40, 0x00 };

        protected readonly byte[] SerPosBytes = { 0xF3, 0x0F, 0x11, 0x81, 0x00, 0x00, 0x00, 0x00 };

        protected static readonly Dictionary<int, string> BuffNames = new Dictionary<int, string>
        {
            {0, ""},
            {1, "Petrification"},
            {2, "Stun"},
            {3, "Sleep"},
            {4, "Daze"},
            {5, "Amnesia"},
            {6, "Pacification"},
            {7, "Silence"},
            {8, "Haste"},
            {9, "Slow"},
            {10, "Slow"},
            {11, "Charmed"},
            {12, ""},
            {13, "Bind"},
            {14, "Heavy"},
            {15, "Blind"},
            {16, ""},
            {17, "Paralysis"},
            {18, "Poison"},
            {19, "Pollen"},
            {20, "TP Bleed"},
            {21, "HP Boost"},
            {22, "HP Penalty"},
            {23, "MP Boost"},
            {24, "MP Penalty"},
            {25, "Attack Up"},
            {26, "Attack Down"},
            {27, "Accuracy Up"},
            {28, "Accuracy Down"},
            {29, "Defense Up"},
            {30, "Defense Down"},
            {31, "Evasion Up"},
            {32, "Evasion Down"},
            {33, "Attack Magic Potency Up"},
            {34, "Attack Magic Potency Down"},
            {35, "Healing Potency Up"},
            {36, "Healing Potency Down"},
            {37, "Magic Defense Up"},
            {38, "Magic Defense Down"},
            {39, "Stun Resistance"},
            {40, "Silence Resistance"},
            {41, ""},
            {42, ""},
            {43, "Weakness"},
            {44, "Brink of Death"},
            {45, "Crafter's Grace"},
            {46, "Gatherer's Grace"},
            {47, "Stealth"},
            {48, "Well Fed"},
            {49, "Medicated"},
            {50, "Sprint"},
            {51, "Strength Down"},
            {52, "Vitality Down"},
            {53, "Physical Damage Up"},
            {54, "Physical Damage Down"},
            {55, "Physical Vulnerability Down"},
            {56, "Physical Vulnerability Up"},
            {57, "Magic Damage Up"},
            {58, "Magic Damage Down"},
            {59, "Magic Vulnerability Down"},
            {60, "Magic Vulnerability Up"},
            {61, "Determination Up"},
            {62, "Determination Down"},
            {63, "Vulnerability Down"},
            {64, "Vulnerability Up"},
            {65, "Critical Skill"},
            {66, "Terror"},
            {67, "Leaden"},
            {68, "Drainstrikes"},
            {69, "Aspirstrikes"},
            {70, "Stunstrikes"},
            {71, "Rampart"},
            {72, "Convalescence"},
            {73, "Awareness"},
            {74, "Sentinel"},
            {75, "Tempered Will"},
            {76, "Fight or Flight"},
            {77, "Bulwark"},
            {78, "Sword Oath"},
            {79, "Shield Oath"},
            {80, "Cover"},
            {81, "Covered"},
            {82, "Hallowed Ground"},
            {83, "Foresight"},
            {84, "Bloodbath"},
            {85, "Maim"},
            {86, "Berserk"},
            {87, "Thrill of Battle"},
            {88, "Holmgang"},
            {89, "Vengeance"},
            {90, "Storm's Eye"},
            {91, "Defiance"},
            {92, "Unchained"},
            {93, "Wrath"},
            {94, "Wrath II"},
            {95, "Wrath III"},
            {96, "Wrath IV"},
            {97, "Infuriated"},
            {98, "Dragon Kick"},
            {99, "Featherfoot"},
            {100, "Internal Release"},
            {101, "Twin Snakes"},
            {102, "Mantra"},
            {103, "Fists of Fire"},
            {104, "Fists of Earth"},
            {105, "Fists of Wind"},
            {106, "Touch of Death"},
            {107, "Opo-opo Form"},
            {108, "Raptor Form"},
            {109, "Coeurl Form"},
            {110, "Perfect Balance"},
            {111, "Greased Lightning"},
            {112, "Greased Lightning II"},
            {113, "Greased Lightning III"},
            {114, "Keen Flurry"},
            {115, "Heavy Thrust"},
            {116, "Life Surge"},
            {117, "Blood for Blood"},
            {118, "Chaos Thrust"},
            {119, "Phlebotomize"},
            {120, "Power Surge"},
            {121, "Disembowel"},
            {122, "Straighter Shot"},
            {123, "Hawk's Eye"},
            {124, "Venomous Bite"},
            {125, "Raging Strikes"},
            {126, "Physical Vulnerability Up"},
            {127, "Quelling Strikes"},
            {128, "Barrage"},
            {129, "Windbite"},
            {130, "Straight Shot"},
            {131, "Downpour of Death"},
            {132, "Quicker Nock"},
            {133, "Swiftsong"},
            {134, "Swiftsong"},
            {135, "Mage's Ballad"},
            {136, "Mage's Ballad"},
            {137, "Army's Paeon"},
            {138, "Army's Paeon"},
            {139, "Foe Requiem"},
            {140, "Foe Requiem"},
            {141, "Battle Voice"},
            {142, "Chameleon"},
            {143, "Aero"},
            {144, "Aero II"},
            {145, "Cleric Stance"},
            {146, "Protect"},
            {147, "Protect"},
            {148, "Raise"},
            {149, "Rebirth"},
            {150, "Medica II"},
            {151, "Stoneskin"},
            {152, "Stoneskin (Physical)"},
            {153, "Stoneskin (Magical)"},
            {154, "Shroud of Saints"},
            {155, "Freecure"},
            {156, "Overcure"},
            {157, "Presence of Mind"},
            {158, "Regen"},
            {159, "Divine Seal"},
            {160, "Surecast"},
            {161, "Thunder"},
            {162, "Thunder II"},
            {163, "Thunder III"},
            {164, "Thundercloud"},
            {165, "Firestarter"},
            {166, "Succor"},
            {167, "Swiftcast"},
            {168, "Manaward"},
            {169, "Manawall"},
            {170, "Apocatastasis"},
            {171, "Ekpyrosis"},
            {172, "Infirmity"},
            {173, "Astral Fire"},
            {174, "Astral Fire II"},
            {175, "Astral Fire III"},
            {176, "Umbral Ice"},
            {177, "Umbral Ice II"},
            {178, "Umbral Ice III"},
            {179, "Bio"},
            {180, "Miasma"},
            {181, "Disease"},
            {182, "Virus"},
            {183, "Fever"},
            {184, "Sustain"},
            {185, "Eye for an Eye"},
            {186, "Eye for an Eye"},
            {187, "Rouse"},
            {188, "Miasma II"},
            {189, "Bio II"},
            {190, "Shadow Flare"},
            {191, "Tri-disaster"},
            {192, "Spur"},
            {193, "Slow"},
            {194, "Shield Wall"},
            {195, "Mighty Guard"},
            {196, "Last Bastion"},
            {197, "Blaze Spikes"},
            {198, "Ice Spikes"},
            {199, "Shock Spikes"},
            {200, "Physical Vulnerability Up"},
            {201, "Stun"},
            {202, "Vulnerability Up"},
            {203, "Boost"},
            {204, "Enfire"},
            {205, "Enblizzard"},
            {206, "Enaero"},
            {207, "Enstone"},
            {208, "Enthunder"},
            {209, "Enwater"},
            {210, "Doom"},
            {211, "Sharpened Knife"},
            {212, "True Sight"},
            {213, "Pacification"},
            {214, "Agitation"},
            {215, "Determination Down"},
            {216, "Paralysis"},
            {217, "Triangulate"},
            {218, "Gathering Rate Up"},
            {219, "Gathering Yield Up"},
            {220, "Gathering Fortune Up"},
            {221, "Truth of Forests"},
            {222, "Truth of Mountains"},
            {223, "Byregot's Ward"},
            {224, "Nophica's Ward"},
            {225, "Prospect"},
            {226, "Haste"},
            {227, "Seduced"},
            {228, "Menphina's Ward"},
            {229, "Nald'thal's Ward"},
            {230, "Llymlaen's Ward"},
            {231, "Thaliak's Ward"},
            {232, "Preparation"},
            {233, "Arbor Call"},
            {234, "Lay of the Land"},
            {235, "Windburn"},
            {236, "Choco Beak"},
            {237, "Choco Regen"},
            {238, "Choco Surge"},
            {239, "The Echo"},
            {240, "Ingenuity"},
            {241, "Blessing of Light"},
            {242, "Arbor Call II"},
            {243, "Lay of the Land II"},
            {244, "Fracture"},
            {245, "Sanction"},
            {246, "Demolish"},
            {247, "Rain of Death"},
            {248, "Circle of Scorn"},
            {249, "Flaming Arrow"},
            {250, "Burns"},
            {251, "Inner Quiet"},
            {252, "Waste Not"},
            {253, "Steady Hand"},
            {254, "Great Strides"},
            {255, "Ingenuity"},
            {256, "Ingenuity II"},
            {257, "Waste Not II"},
            {258, "Manipulation"},
            {259, "Innovation"},
            {260, "Reclaim"},
            {261, "Comfort Zone"},
            {262, "Steady Hand II"},
            {263, "Vulnerability Down"},
            {264, "Flesh Wound"},
            {265, "Stab Wound"},
            {266, "Concussion"},
            {267, "Burns"},
            {268, "Frostbite"},
            {269, "Windburn"},
            {270, "Sludge"},
            {271, "Electrocution"},
            {272, "Dropsy"},
            {273, "Bleeding"},
            {274, "Recuperation"},
            {275, "Poison +1"},
            {276, "Voice of Valor"},
            {277, "Voice of Fortitude"},
            {278, "Relentless March"},
            {279, "Rehabilitation"},
            {280, "Bind"},
            {281, "Physical Damage Down"},
            {282, "Mana Modulation"},
            {283, "Dropsy"},
            {284, "Burns"},
            {285, "Frostbite"},
            {286, "Windburn"},
            {287, "Sludge"},
            {288, "Electrocution"},
            {289, "Dropsy"},
            {290, "Determination Up"},
            {291, "Hundred Fists"},
            {292, "Fetters"},
            {293, "Skill Speed Up"},
            {294, "Spell Speed Up"},
            {295, "Goldbile"},
            {296, "Hysteria"},
            {297, "Galvanize"},
            {298, "Sacred Soil"},
            {299, "Sacred Soil"},
            {300, "Determination Up"},
            {301, "Critical Strikes"},
            {302, "Gold Lung"},
            {303, "Burrs"},
            {304, "Aetherflow"},
            {305, "The Dragon's Curse"},
            {306, "Inner Dragon"},
            {307, "Voice of Valor"},
            {308, "Voice of Fortitude"},
            {309, "Relentless March"},
            {310, "Curl"},
            {311, "Earthen Ward"},
            {312, "Earthen Fury"},
            {313, "Radiant Shield"},
            {314, "Inferno"},
            {315, "Whispering Dawn"},
            {316, "Fey Covenant"},
            {317, "Fey Illumination"},
            {318, "Fey Glow"},
            {319, "Fey Light"},
            {320, "Bleeding"},
            {321, "Gungnir"},
            {322, "Crystal Veil"},
            {323, "Reduced Immunity"},
            {324, "Greenwrath"},
            {325, "Invincibility"},
            {326, "Lightning Charge"},
            {327, "Ice Charge"},
            {328, "Heart of the Mountain"},
            {329, "Modification"},
            {330, "Haste"},
            {331, "Magic Vulnerability Down"},
            {332, "Determination Up"},
            {333, "Allagan Rot"},
            {334, "Allagan Immunity"},
            {335, "Firestream"},
            {336, "Sequence AB1"},
            {337, "Sequence AP1"},
            {338, "Sequence AS1"},
            {339, "Bleeding"},
            {340, "Physical Field"},
            {341, "Aetherial Field"},
            {342, "Repelling Spray"},
            {343, "Bleeding"},
            {344, "Neurolink"},
            {345, "Recharge"},
            {346, "Waxen Flesh"},
            {347, "Pox"},
            {348, "Disseminate"},
            {349, "Steel Scales"},
            {350, "Vulnerability Down"},
            {351, "Rancor"},
            {352, "Spjot"},
            {353, "Brave New World"},
            {354, "Live off the Land"},
            {355, "What You See"},
            {356, "Eat from the Hand"},
            {357, "In Control"},
            {358, "Snowman"},
            {359, "Fey Fire"},
            {360, "Meat and Mead"},
            {361, "That Which Binds Us"},
            {362, "Proper Care"},
            {363, "Back on Your Feet"},
            {364, "Reduced Rates"},
            {365, "The Heat of Battle"},
            {366, "A Man's Best Friend"},
            {367, "Earth and Water"},
            {368, "Helping Hand"},
            {369, "Viscous Aetheroplasm"},
            {370, "Siren Song"},
            {371, "Zombification"},
            {372, "Brood Rage"},
            {373, "Blight"},
            {374, "Corrupted Crystal"},
            {375, "Suppuration"},
            {376, "Searing Wind"},
            {377, "Infernal Fetters"},
            {378, "Death Throes"},
            {379, "Thermal Low"},
            {380, "Thermal High"},
            {381, "Testudo"},
            {382, "Testudo Ward"},
            {383, ""},
            {384, "Thrill of War"},
            {385, "Full Swing"},
            {386, "Somersault"},
            {387, "Fetter Ward"},
            {388, "Impulse Rush"},
            {389, "Skewer"},
            {390, "Sacred Prism"},
            {391, "Phantom Dart"},
            {392, "Misty Veil"},
            {393, "Wither"},
            {394, "Focalization"},
            {395, "Aetheric Burst"},
            {396, "Equanimity"},
            {397, "Attunement"},
            {398, "Astral Realignment"},
            {399, "Corporeal Return"},
            {400, "Charge"},
            {401, "Death Grip"},
            {402, "Thrown for a Loop"},
            {403, "Determination Up"},
            {404, "Transporting"},
            {405, "Bewildered"},
            {406, "Vulnerability Down"},
            {407, "Dust Poisoning"},
            {408, "Storm's Path"},
            {409, "Holmgang"},
            {410, "Antibody"},
            {411, "Inner Beast"},
            {412, "Hover"},
            {413, "Mark Up"},
            {414, "Seal Sweetener"},
            {415, "Regain"},
            {416, "Transparent"},
            {417, ""},
            {418, "Physical Vulnerability Down"},
            {419, "Misty Veil"}
        };

        protected readonly Dictionary<int, string> Zones = new Dictionary<int, string>
        {
            {1, "Default"},
            {2, "Collision Test"},
            {3, "Battle Test"},
            {4, "PvP Test"},
            {5, "Cutscene Test"},
            {6, "Central Thanalan"},
            {7, "Central Shroud"},
            {8, "New Gridania"},
            {9, "Central Shroud"},
            {10, "Lower La Noscea"},
            {11, "The Tam-Tara Deepcroft"},
            {13, "Bayohne Memorial Zoo"},
            {14, "NPC Spawn Test"},
            {15, "Retainer Test"},
            {16, "unknown"},
            {17, "unknown"},
            {18, "unknown"},
            {19, "Leve Test"},
            {20, "unknown"},
            {21, "unknown"},
            {22, "unknown"},
            {24, "unknown"},
            {25, "unknown"},
            {128, "Limsa Lominsa Upper Decks"},
            {129, "Limsa Lominsa Lower Decks"},
            {130, "Uldah - Steps of Nald"},
            {131, "Uldah - Steps of Thal"},
            {132, "New Gridania"},
            {133, "Old Gridania"},
            {134, "Middle La Noscea"},
            {135, "Lower La Noscea"},
            {136, "unknown"},
            {137, "Eastern La Noscea"},
            {138, "Western La Noscea"},
            {139, "Upper La Noscea"},
            {140, "Western Thanalan"},
            {141, "Central Thanalan"},
            {145, "Eastern Thanalan"},
            {146, "Southern Thanalan"},
            {147, "Northern Thanalan"},
            {148, "Central Shroud"},
            {152, "East Shroud"},
            {153, "South Shroud"},
            {154, "North Shroud"},
            {155, "Coerthas Central Highlands"},
            {156, "Mor Dhona"},
            {157, "Sastasha"},
            {158, "Brayfloxs Longstop"},
            {159, "The Wanderers Palace"},
            {160, "??????????1????"},
            {161, "Copperbell Mines"},
            {162, "Halatali"},
            {163, "The Sunken Temple of Qarn"},
            {164, "The Tam-Tara Deepcroft"},
            {166, "Haukke Manor"},
            {167, "???????????"},
            {168, "??????????????"},
            {169, "The Thousand Maws of Toto-Rak"},
            {170, "Cutters Cry"},
            {171, "Dzemael Darkhold"},
            {172, "Aurum Vale"},
            {173, "????????1(??"},
            {174, "unknown"},
            {175, "The Floating Coliseum"},
            {176, "Mordion Gaol"},
            {177, "Mizzenmast Inn"},
            {178, "The Hourglass"},
            {179, "The Roost"},
            {180, "Outer La Noscea"},
            {1181, "Limsa Lominsa"},
            {1182, "Uldah - Steps of Nald"},
            {1183, "New Gridania"},
            {184, "unknown"},
            {185, "unknown"},
            {186, "unknown"},
            {187, "unknown"},
            {188, "unknown"},
            {189, "unknown"},
            {190, "Central Shroud"},
            {191, "East Shroud"},
            {192, "South Shroud"},
            {197, "unknown"},
            {198, "Command Room"},
            {199, "???????????"},
            {200, "???????????"},
            {201, "unknown"},
            {202, "Bowl of Embers"},
            {203, "unknown"},
            {204, "Seat of the First Bow"},
            {205, "Lotus Stand"},
            {206, "???????(?)"},
            {207, "???????(?)"},
            {208, "???????(?)"},
            {209, "unknown"},
            {210, "Heart of the Sworn"},
            {211, "The Fragrant Chamber"},
            {212, "The Waking Sands"},
            {213, "unknown"},
            {214, "Middle La Noscea"},
            {215, "Western Thanalan"},
            {216, "Central Thanalan"},
            {217, "Castrum Meridianum"},
            {218, "North Shroud"},
            {219, "Central Shroud"},
            {220, "South Shroud"},
            {221, "Upper La Noscea"},
            {222, "Lower La Noscea"},
            {223, "Coerthas Central Highlands"},
            {224, "Castrum Meridianum Baileys"},
            {225, "Central Shroud"},
            {226, "Central Shroud"},
            {227, "Central Shroud"},
            {228, "North Shroud"},
            {229, "South Shroud"},
            {230, "Central Shroud"},
            {231, "South Shroud"},
            {232, "South Shroud"},
            {233, "Central Shroud"},
            {234, "East Shroud"},
            {235, "South Shroud"},
            {236, "South Shroud"},
            {237, "Central Shroud"},
            {238, "Old Gridania"},
            {239, "Central Shroud"},
            {240, "North Shroud"},
            {241, "unknown"},
            {242, "unknown"},
            {243, "unknown"},
            {244, "unknown"},
            {245, "unknown"},
            {246, "unknown"},
            {247, "unknown"},
            {248, "Central Thanalan"},
            {249, "Lower La Noscea"},
            {250, "??????????????(?)"},
            {251, "Uldah - Steps of Nald"},
            {252, "Middle La Noscea"},
            {253, "Central Thanalan"},
            {254, "Uldah - Steps of Nald"},
            {255, "Western Thanalan"},
            {256, "Eastern Thanalan"},
            {257, "Eastern Thanalan"},
            {258, "Central Thanalan"},
            {259, "Uldah - Steps of Nald"},
            {260, "Southern Thanalan"},
            {261, "Southern Thanalan"},
            {262, "Lower La Noscea"},
            {263, "Western La Noscea"},
            {264, "Lower La Noscea"},
            {265, "Lower La Noscea"},
            {266, "Eastern Thanalan"},
            {267, "Western Thanalan"},
            {268, "Eastern Thanalan"},
            {269, "Western Thanalan"},
            {270, "Central Thanalan"},
            {271, "Central Thanalan"},
            {272, "Middle La Noscea"},
            {273, "Western Thanalan"},
            {274, "Uldah - Steps of Nald"},
            {275, "Eastern Thanalan"},
            {276, "Hall of Summoning"},
            {277, "East Shroud"},
            {278, "Western Thanalan"},
            {279, "Lower La Noscea"},
            {280, "Western La Noscea"},
            {281, "unknown"},
            {282, "Limsa Lominsa Upper Decks"},
            {283, "Limsa Lominsa Upper Decks"},
            {284, "Limsa Lominsa Upper Decks"}
        };
    }
}
